hugovk/norwegianblue

src/norwegianblue/__init__.py, tests/test_norwegianblue.py
Like https://github.com/hugovk/norwegianblue/pull/2, `support` can be either a date or Boolean:
`eol bootstrap`
|  cycle  | latest |  release   | support |    eol     |
| ------- | ------ | ---------- | ------- | ---------- |
| 5.x LTS | 5.0.1  | 2021-05-05 | True    | False      |
| 4.x LTS | 4.6.0  | 2018-01-18 | False   | 2022-11-01 |
| 3.x     | 3.4.1  | 2013-08-19 | False   | 2019-07-24 |
| 2.x     | 2.3.2  | 2013-07-18 | False   | 2013-08-19 |
```json
[
{
"cycle": "5.x",
"release": "2021-05-05",
"eol": false,
"support": true,
"lts": true,
"latest": "5.0.1"
},
{
"cycle": "4.x",
"release": "2018-01-18",
"eol": "2022-11-01",
"latest": "4.6.0",
"lts": true,
"support": false
},
{
"cycle": "3.x",
"release": "2013-08-19",
"eol": "2019-07-24",
"latest": "3.4.1",
"support": false
},
{ …
```
=> Handle Boolean "support" and Boolean and date "discontinued"

src/norwegianblue/__init__.py, src/norwegianblue/cli.py, tests/test_norwegianblue.py
Fixes #10.
And set `'all'` as the default:
```console
$ eol --help
usage: eol [-h] [-f {html,json,markdown,rst,tsv}] [-c {yes,no,auto}] [-v] [-V] [tool]
CLI to show end-of-life dates for tools and technologies.
positional arguments:
tool                  Tool to check, or 'all' to list all available (default: all)
optional arguments:
-h, --help            show this help message and exit
-f {html,json,markdown,rst,tsv}, --format {html,json,markdown,rst,tsv}
The format of output (default: markdown)
-c {yes,no,auto}, --color {yes,no,auto}
color terminal output (default: auto)
-v, --verbose         Print debug messages to stderr (default: False)
-V, --version         show program's version number and exit
```
```console
$ eol all
alpine
amazon-linux
android
bootstrap
centos
debian
django …
```
=> List all tools with 'eol all'

requirements.txt, setup.cfg, src/norwegianblue/__init__.py
platformdirs is a better-maintained fork.
https://github.com/ActiveState/appdirs/issues/79
=> Replace appdirs with platformdirs

requirements.txt, setup.cfg, src/norwegianblue/__init__.py, src/norwegianblue/cli.py, tests/data/expected_output.py
pytablewriter==0.62.0
See `Debian 11 "Bullseye`:
```console
$ eol debian
|          cycle           | latest |  release   |    eol     |                            link                             |
| ------------------------ | ------ | ---------- | ---------- | ----------------------------------------------------------- |
| Debian 11 "Bullseye      | 11.0   | 2021-08-14 | 2026-08-15 | https://www.debian.org/News/2021/20210814                   |
| Debian 10 "Buster        | 10.10  | 2019-07-06 | 2024-06-01 | https://www.debian.org/News/2021/20210619                   |
| Debian 9 "Stretch" (LTS) | 9.12   | 2017-06-17 | 2022-06-30 | https://lists.debian.org/debian-announce/2020/msg00001.html |
| Debian 9 "Stretch        | 9.12   | 2017-06-17 | 2020-01-01 | …
```
=> Bump minimum pytablewriter to fix trailing quotes

.github/workflows/deploy.yml, .github/workflows/labels.yml, .github/workflows/lint.yml, .github/workflows/test.yml, .pre-commit-config.yaml, setup.cfg, src/norwegianblue/__init__.py, tox.ini
https://github.com/hugovk/norwegianblue/pull/31 wasn't finished! Let's finish it here, and only for 3.7+ so we can use `from __future__ import annotations`. 3.6 is EOL in a couple of months anyway: https://endoflife.date/python
---
Unrelated, let's also use `python -m build` instead of `python setup.py sdist --format=gztar bdist_wheel` for building.
https://packaging.python.org/tutorials/packaging-projects/#generating-distribution-archives
Plus some other minor workflow updates.
=> Add support for Python 3.7-3.8 and PyPy

src/norwegianblue/__init__.py
Here's how to use `python -X importtime` and tuna to identify bottlenecks: https://medium.com/alan/how-we-improved-our-python-backend-start-up-time-2c33cd4873c8
Running:
```sh
python -X importtime -c "import norwegianblue; norwegianblue.norwegianblue('python')" 2> import.log
tuna import.log
```
Shows importing httpx can take ~250 ms, which is unnecessary when loading a cached file (i.e. we've already run the command today).
Let's show tuna output from earlier speedups.
Slow imports: httpx, pkg_resources, pytablewriter.
704 ms.
Use PrettyTable for default Markdown output, it's much lighter to import.
704 -> 599 ms.
599 -> 353 ms.
599 -> 134 ms.
=> Speedup: only import httpx if needed

requirements.txt, setup.cfg, src/norwegianblue/__init__.py, tests/data/expected_output.py
And require PrettyTable 2.4.0 because it now adds colons in the column to align the rendered output.
And update tests to match.
=> Only align necessary columns and not whole table

src/norwegianblue/__init__.py, tests/data/expected_output.py, tests/test_norwegianblue.py
| cycle   | latest |  release   |  support   |    eol     |
|:--------|:-------|:----------:|:----------:|:----------:|
| 5.3 LTS | 5.3.9  | 2021-05-31 | 2022-01-01 | 2022-01-01 |
| 5.2 LTS | 5.2.14 | 2020-11-30 | 2021-07-21 | 2021-07-21 |
| 5.1 LTS | 5.1.11 | 2020-05-31 | 2021-01-21 | 2021-01-21 |
| 5.0 LTS | 5.0.11 | 2019-11-21 | 2020-07-21 | 2020-07-21 |
| 4.4 LTS | 4.4.32 | 2019-11-21 | 2022-11-21 | 2023-11-21 |
| 4.3 LTS | 4.3.11 | 2019-05-01 | 2020-01-01 | 2020-07-01 |
| 4.2 LTS | 4.2.12 | 2018-11-01 | 2019-07-01 | 2020-01-01 |
| 4.1 LTS | 4.1.13 | 2018-05-01 | 2019-01-01 | 2019-07-01 |
| 4.0 LTS | 4.0.15 | 2017-11-01 | 2018-07-01 | 2019-01-01 |
| 3.4 LTS | 3.4.49 | 2017-11-01 | 2020-11-01 | 2021-11-01 |
| 3.3 LTS | 3.3.18 | 2017-05-01 | 2018-01-01 | 2018-07-01 |
| 3.2 LTS | 3.2.14 …
=> Fix labelling LTS releases

src/norwegianblue/cli.py
```console
$ eol --help
usage: eol [-h] [-f {html,json,markdown,rst,tsv}] [-c {yes,no,auto}]
[--clear-cache] [-v] [-V]
[product]
CLI to show end-of-life dates for a number of products, from
https://endoflife.date
positional arguments:
product               Product to check, or 'all' to list all available
(default: all)
options:
-h, --help            show this help message and exit
-f {html,json,markdown,rst,tsv}, --format {html,json,markdown,rst,tsv}
The format of output (default: markdown)
-c {yes,no,auto}, --color {yes,no,auto}
color terminal output (default: auto)
--clear-cache         Clear cache before running (default: False)
-v, --verbose         Print debug messages to stderr (default: False)
-V, --version         show program's version number and exit
```
```console
$ eol --help …
```
=> Add examples to --help

.pre-commit-config.yaml, setup.cfg, src/norwegianblue/__init__.py
```console
$ eol node --clear-cache
Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.10/bin/eol", line 33, in <module>
sys.exit(load_entry_point('norwegianblue', 'console_scripts', 'eol')())
File "/Users/hugo/github/norwegianblue/src/norwegianblue/cli.py", line 61, in main
output = norwegianblue.norwegianblue(
File "/Users/hugo/github/norwegianblue/src/norwegianblue/__init__.py", line 128, in norwegianblue
r.raise_for_status()
File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httpx/_models.py", line 1507, in raise_for_status
raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Redirect response '301 Moved Permanently' for url 'https://endoflife.date/api/node.json'
Redirect …
```
=> httpx: Enable following redirects

README.md, scripts/run_command.py, tox.ini
Similar to https://github.com/hugovk/pypistats/pull/293.
https://nedbatchelder.com/code/cog
https://github.com/nedbat/cog
Update with:
```sh
python -m pip install cog
cog -Pr README.md
```
Or:
```sh
tox -e cog
```
=> Use cog to update README usage

src/norwegianblue/__init__.py
```console
$ eol python -v
Human URL:	https://endoflife.date/python
API URL:	https://endoflife.date/api/python.json
Source URL:	https://github.com/endoflife-date/endoflife.date/blob/master/products/python.md
Cache file:	/Users/hugo/Library/Caches/norwegianblue/2021-12-07-https-endoflife-date-api-python-json.json
Cache file exists
| cycle | latest |  release   |    eol     |
|:------|:-------|:----------:|:----------:|
| 3.10  | 3.10.0 | 2021-10-04 | 2026-10-04 |
| 3.9   | 3.9.9  | 2020-10-05 | 2025-10-05 |
| 3.8   | 3.8.12 | 2019-10-14 | 2024-10-14 |
| 3.7   | 3.7.12 | 2018-06-27 | 2023-06-27 |
| 3.6   | 3.6.15 | 2016-12-23 | 2021-12-23 |
| 3.5   | 3.5.10 | 2015-09-30 | 2020-09-13 |
| 3.4   | 3.4.10 | 2014-03-16 | 2019-03-18 |
| 3.3   | 3.3.7  | 2012-09-29 | 2017-09-29 |
| 2.7   | 2.7.18 …
```
=> Add source URL to `--verbose`

tests/test_norwegianblue.py
Dates are coloured based on the current time, and passed when this test was written.
Freeze time to match correct behaviour at that time.
=> Freeze time to fix colour test

src/norwegianblue/__init__.py
Follow on from https://github.com/hugovk/norwegianblue/pull/68.
=> Fix status code logging and use lazy % formatting in logging functions

tests/test_norwegianblue.py
A test started failing (e.g. https://github.com/hugovk/norwegianblue/pull/73) because time wasn't frozen and one product has moved from green to yellow.
=> Freeze time to fix test

.github/dependabot.yml, .github/workflows/deploy.yml, .github/workflows/release-drafter.yml, .github/workflows/test.yml, .pre-commit-config.yaml, README.md, setup.cfg, tox.ini
In beta next week, full release in October: https://peps.python.org/pep-0664/
Plus update some config.
=> Support Python 3.11

src/norwegianblue/__init__.py, tests/data/expected_output.py, tests/test_norwegianblue.py
Following changes made in https://github.com/endoflife-date/endoflife.date/pull/1264.
Main thing is to re-order them to something sensible, and we also have a new `latestReleaseDate`.
Might rename headers in another PR, like `latestReleaseDate` to `latest release date` (or something shorter).
```console
$ eol python
[:~/github/norwegianblue] main* ± eol python
| cycle | latest |    eol     | latestReleaseDate | releaseDate |
|:------|:-------|:----------:|:-----------------:|:-----------:|
| 3.10  | 3.10.5 | 2026-10-04 |     2022-06-06    |  2021-10-04 |
| 3.9   | 3.9.13 | 2025-10-05 |     2022-05-17    |  2020-10-05 |
| 3.8   | 3.8.13 | 2024-10-14 |     2022-03-16    |  2019-10-14 |
| 3.7   | 3.7.13 | 2023-06-27 |     2022-03-16    |  2018-06-26 |
| 3.6   | 3.6.15 | 2021-12-23 | …
```
=> Update for `release` renamed to `releaseDate` in API

src/norwegianblue/__init__.py
https://endoflife.date/macos looks like:
Note the newer ones are macOS: "macOS 10.12 (Sierra)" and older are OS X: "OS X 10.11 (El Capitan)".
https://raw.githubusercontent.com/endoflife-date/endoflife.date/master/products/macos.md looks like:
```md
---
title: macOS
alternate_urls:
-   /mac
category: os
sortReleasesBy: releaseDate
releaseLabel: "macOS __RELEASE_CYCLE__ (__CODENAME__)"
auto:
-   custom: true
releases:
-   releaseCycle: "12"
codename: "Monterey"
eol: false
link: https://support.apple.com/HT212585
releaseDate: 2021-10-25
latestReleaseDate: 2022-09-12
latest: '12.6'
-   releaseCycle: "11"
codename: "Big Sur"
eol: false
link: https://support.apple.com/HT211896
releaseDate: 2020-11-12
latestReleaseDate: 2022-09-12
latest: '11.7'
-   releaseCycle: "10.15"
codename: "Catalina" …
```
=> Omit the releaseLabel column

requirements.txt, tests/test_norwegianblue.py
Since https://github.com/termcolor/termcolor/releases/tag/2.1.0 and https://github.com/termcolor/termcolor/pull/25, we need to make sure colour is enabled for these tests.
Fixes failures seen in https://github.com/hugovk/norwegianblue/pull/103, https://github.com/hugovk/norwegianblue/pull/104, https://github.com/hugovk/norwegianblue/pull/105, https://github.com/hugovk/norwegianblue/pull/106.
=> termcolor now disables colour if not tty, but FORCE_COLOR for colour tests

tests/test_norwegianblue.py
Follow up to #107, mock the env var instead of setting it directly, so as not to affect other tests.
=> Mock instead of setting real env var

src/norwegianblue/__init__.py, src/norwegianblue/cli.py, tests/data/expected_output.py, tests/test_norwegianblue.py
Fixes #110.
Add CSV format output.
For example:
```console
$ eol python --format csv
"cycle","release","latest","latest release","eol"
"3.11","2022-10-24","3.11.0","2022-10-24","2027-10-24"
"3.10","2021-10-04","3.10.8","2022-10-11","2026-10-04"
"3.9","2020-10-05","3.9.15","2022-10-11","2025-10-05"
"3.8","2019-10-14","3.8.15","2022-10-11","2024-10-14"
"3.7","2018-06-26","3.7.15","2022-10-10","2023-06-27"
"3.6","2016-12-22","3.6.15","2021-09-03","2021-12-23"
"3.5","2015-09-12","3.5.10","2020-09-05","2020-09-13"
"3.4","2014-03-15","3.4.10","2019-03-18","2019-03-18"
"3.3","2012-09-29","3.3.7","2017-09-19","2017-09-29"
"2.7","2010-07-03","2.7.18","2020-04-19","2020-01-01"
"2.6","2008-10-01","2.6.9","2013-10-29","2013-10-29"
```
=> Add CSV format output

src/norwegianblue/__init__.py, tests/data/expected_output.py
Better to show the codename (e.g. "Jammy Jellyfish") after the cycle name (e.g. "22.04 LTS"), also more closely matches https://endoflife.date/ubuntu
```console
$ eol ubuntu
┌───────────┬────────────┬─────────┬────────────────┬────────────┬────────────┬─────────────────┬──────────────────────────────────────────────────────┐
│ cycle     │  release   │ latest  │ latest release │  support   │    eol     │     codename    │ link                                                 │
├───────────┼────────────┼─────────┼────────────────┼────────────┼────────────┼─────────────────┼──────────────────────────────────────────────────────┤
│ 22.10     │ 2022-10-20 │ 22.10   │   2022-10-20   │ 2023-07-20 │ 2023-07-20 │   Kinetic Kudu  │ https://wiki.ubuntu.com/KineticKudu/ReleaseNotes/    │
│ 22.04 LTS │ …
```
=> Output codename after cycle

.github/workflows/test.yml, pyproject.toml, src/norwegianblue/__init__.py, tests/test_norwegianblue.py
https://github.com/termcolor/termcolor/releases/tag/2.1.0 added support to detect if colour can be used by the terminal, so we can depend on `termcolor>2.1` and remove that code from here.
Also bump PyPy3.8 to PyPy3.9 on CI.
=> Let termcolor 2.1 determine if colour can be used

.pre-commit-config.yaml, pyproject.toml
The new Black can autodetect the target version from `project.requires-python` in `pyproject.toml`.
https://ichard26.github.io/blog/2023/01/black-23.1.0/#better-default-for---target-version-if-pep-621-python-requires-is-available
=> Update pre-commit: Black and pyproject-fmt changes

pyproject.toml, requirements.txt, src/norwegianblue/__init__.py, src/norwegianblue/cli.py, tests/test_norwegianblue.py
If the product is not found, suggest the closest one.
For example:
```console
$ eol androd
Product 'androd' not found, run 'eol all' for list. Did you mean: 'android'?
$ eol pythn
Product 'pythn' not found, run 'eol all' for list. Did you mean: 'python'?
$ eol samsung
Product 'samsung' not found, run 'eol all' for list. Did you mean: 'samsung-mobile'?
```
Similar to the improved error messages in Python [3.10](https://docs.python.org/3/whatsnew/3.10.html#attributeerrors) and [3.12](https://docs.python.org/3.12/whatsnew/3.12.html#improved-error-messages). 
Also refactor `norwegianblue()` to raise `ValueError` on 404 instead of returning.
=> If product not found, offer a suggestion

src/norwegianblue/__init__.py, src/norwegianblue/_cache.py
Raises a deprecation warning in Python 3.12: https://github.com/python/cpython/issues/103857.
Committed via https://github.com/asottile/all-repos
=> Replace deprecated utcnow() with now(utc)

src/norwegianblue/__init__.py
Fixes https://github.com/hugovk/norwegianblue/issues/154.
This fixes a bug. The "cycle" and "latest" columns should be left aligned (for at least Markdown and pretty formats).
But when using pretty format, the headers are shown in bold, which means the alignment isn't set correctly because we've already modified the header text to add ANSI formatting.
The Markdown format correctly left aligns the cycle and latest columns:
```console
❯ eol ubuntu --format md
| cycle     |      codename     |  release   | latest  | latest release |  support   |    eol     | extendedSupport |
|:----------|:-----------------:|:----------:|:--------|:--------------:|:----------:|:----------:|:---------------:|
| 23.04     |   Lunar Lobster   | 2023-04-20 | 23.04   |   2023-04-20   | 2024-01-20 | 2024-01-20 | …
```
=> Fix left alignment of cycle column when header is bold for pretty format

.github/workflows/deploy.yml, .github/workflows/test.yml
Committed via https://github.com/asottile/all-repos
=> Remove default 'cache-dependency-path: pyproject.toml'

pyproject.toml, requirements.txt, src/norwegianblue/__init__.py
I just heard about `difflib.get_close_matches` which is in the standard library, so we don't need to install the third-party [thefuzz](https://pypi.org/project/thefuzz/) for the "Did you mean?" suggestions.
https://docs.python.org/3/library/difflib.html#difflib.get_close_matches
```console
❯ eol pthon
Product 'pthon' not found, run 'eol all' for list. Did you mean: 'python'? [Y/n]
...
❯ eol hph
Product 'hph' not found, run 'eol all' for list. Did you mean: 'php'? [Y/n]
...
❯ eol androd
Product 'androd' not found, run 'eol all' for list. Did you mean: 'android'? [Y/n]
...
❯ eol samsung
Product 'samsung' not found, run 'eol all' for list. Did you mean: 'samsung-mobile'? [Y/n]
```
Follow on from https://github.com/hugovk/norwegianblue/pull/132 and …
=> Replace 3rd-party thefuzz with stdlib `difflib.get_close_matches`

README.md, src/norwegianblue/cli.py
I thought the CLI might be a bit easier to use if we change the format arguments from things like `--format md` and `-f rst` to direct `--md` and `--rst`, and so on.
Also group the different formatting options in the `--help` text.
I've left the old `-f`/`--format` options in for now, they print a deprecation warning, and can be removed in a later release. 
What do you think?
```console
❯ eol -h
usage: eol [-h] [-f {html,json,md,markdown,pretty,rst,csv,tsv,yaml}] [-c {yes,no,auto}] [--clear-cache] [-v] [-V] [-w]
[product ...]
CLI to show end-of-life dates for a number of products, from https://endoflife.date
For example:
* `eol python` to see Python EOLs
* `eol ubuntu` to see Ubuntu EOLs
* `eol centos fedora` to see CentOS and Fedora EOLs
* `eol all` or `eol` to list all available …
```
=> Refactor output arguments from '--format md' to '--md' etc.

README.md
pipx is my preferred way of installing Python-based CLIs and I can confirm that this works for `norwegianblue`.
Cheers!
=> Document installation using pipx

.flake8, .github/workflows/deploy.yml, .github/workflows/labels.yml, .github/workflows/lint.yml, .github/workflows/require-pr-label.yml
Use https://github.com/hynek/build-and-inspect-python-package for releasing.
Add permissions to other workflows.
Remove `.flake8` config now we use Ruff.
=> Use hynek/build-and-inspect-python-package for releasing

.pre-commit-config.yaml, scripts/run_command.py, src/norwegianblue/__init__.py, src/norwegianblue/_cache.py, src/norwegianblue/_data.py, tests/test_norwegianblue.py
Not yet ready to enable mypy in pre-commit.
=> Add some more type hints

src/norwegianblue/cli.py
```console
$ eol pytho
Product 'pytho' not found, run 'eol all' for list. Did you mean: 'python'? [Y/n] y
Traceback (most recent call last):
File "/Users/hugo/github/norwegianblue/src/norwegianblue/cli.py", line 132, in main
output = norwegianblue.norwegianblue(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/hugo/github/norwegianblue/src/norwegianblue/__init__.py", line 66, in norwegianblue
raise ValueError(msg)
ValueError: Product 'pytho' not found, run 'eol all' for list. Did you mean: 'python'?
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.11/bin/eol", line 8, in <module>
sys.exit(main())
^^^^^^
File "/Users/hugo/github/norwegianblue/src/norwegianblue/cli.py", line 146, in main …
```
=> Fix `KeyError` after 'Did you mean?' correction

tests/test_norwegianblue.py
The CI started failing like this:
Because the `FORCE_COLOR=1` from the workflow is being passed to the tests, and adding colour to the output. 
Let's instead disable colour for the affected tests by setting `NO_COLOR` to `True`, like we do with another, because colour isn't relevant to these tests.
=> Disable colour to fix CI

src/norwegianblue/__init__.py, src/norwegianblue/cli.py, tests/test_norwegianblue.py
When there are no suggestions returned by **suggest_product()** we get an IndexError from attempting to read the first element of an empty list.
I changed it such that if there are no suggestions, no [Y/n] option will be given; the prompt will only state that the search term is not found and exit immediately.
```bash
$ eol julia
Traceback (most recent call last):
File "/home/tingfeng/miniconda3/bin/eol", line 8, in <module>
sys.exit(main())
^^^^^^
File "/home/tingfeng/miniconda3/lib/python3.11/site-packages/norwegianblue/cli.py", line 132, in main
output = norwegianblue.norwegianblue(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/tingfeng/miniconda3/lib/python3.11/site-packages/norwegianblue/__init__.py", line 64, in norwegianblue
suggestion = suggest_product(product)
^^^^^^^^^^^^^^^^^^^^^^^^ …
```
=> Fix IndexError when there are no suggestions

README.md, src/norwegianblue/__init__.py, src/norwegianblue/_cache.py, src/norwegianblue/cli.py, tests/test_cache.py, tests/test_norwegianblue.py
Closes #192
Default behavior remains unchanged; Single product -> No title, Multiple products -> Show title for each product
If `--show-title` is `yes`, title is always shown. When `no`, title is never shown.
=> Add --show-title flag

src/norwegianblue/cli.py
Bugfix for **args.show_title** not being used after accepting a `Did you mean [Y/n]` suggestion.
=> Use `args.show_title` after accepting suggestion

.gitignore, pyproject.toml, src/norwegianblue/__init__.py
With Python 3.12.4:
```sh
python -X importtime -c "import norwegianblue" 2> import.log && tuna import.log
```
Cuts out the 22ms `importlib.metadata` import.
```console
❯ hyperfine -w 8 "eol --version"
Benchmark 1: eol --version
Time (mean ± σ):      55.1 ms ±   3.8 ms    [User: 43.3 ms, System: 10.4 ms]
Range (min … max):    50.9 ms …  71.4 ms    53 runs
```
```console
❯ hyperfine -w 8 "eol --version"
Benchmark 1: eol --version
Time (mean ± σ):      38.2 ms ±   1.7 ms    [User: 29.6 ms, System: 7.3 ms]
Range (min … max):    35.3 ms …  41.9 ms    73 runs
```
=> Generate `__version__` at build to avoid slow `importlib.metadata` import

.github/workflows/test.yml, .gitignore, .pre-commit-config.yaml, pyproject.toml, src/norwegianblue/__init__.py, tox.ini
Python 3.8 is end-of-life next month:
* https://devguide.python.org/versions/
* https://peps.python.org/pep-0569/#lifespan
=> Drop support for Python 3.8

.github/workflows/lint.yml
No Actions cache: 1m 5s
https://github.com/hugovk/norwegianblue/actions/runs/11332579656/job/31514988544
With Actions cache: 19s
https://github.com/hugovk/norwegianblue/actions/runs/11332596790/job/31515040851
No Actions cache: 44s
https://github.com/hugovk/norwegianblue/actions/runs/11332607215/job/31515072047
With Actions cache: 13s
https://github.com/hugovk/norwegianblue/actions/runs/11332620769/job/31515116728
=> Use pre-commit-uv for lint

pyproject.toml, requirements.txt, src/norwegianblue/__init__.py
https://github.com/prettytable/prettytable/releases/tag/3.12.0
https://github.com/prettytable/prettytable/pull/329
Fixes:
```python
tests/test_norwegianblue.py::TestNorwegianBlue::test_norwegianblue_formats[markdown0]
/Users/hugo/github/norwegianblue/src/norwegianblue/__init__.py:230: DeprecationWarning: the 'MARKDOWN' constant is deprecated, use the 'TableStyle' enum instead
from prettytable import MARKDOWN, SINGLE_BORDER, PrettyTable
tests/test_norwegianblue.py::TestNorwegianBlue::test_norwegianblue_formats[markdown0]
/Users/hugo/github/norwegianblue/src/norwegianblue/__init__.py:230: DeprecationWarning: the 'SINGLE_BORDER' constant is deprecated, use the 'TableStyle' enum instead
from prettytable import MARKDOWN, SINGLE_BORDER, PrettyTable
```
=> Replace deprecated constants with enums

src/norwegianblue/__init__.py, tests/test_norwegianblue.py
Fixes https://github.com/hugovk/norwegianblue/issues/228.
For programmatic use, return the decoded JSON before turning it into a formatted string.
So there's no need to do something like parse a JSON string back into a Python data structure.
=> Use `format=None` to return raw Python data structure

src/norwegianblue/cli.py
```console
❯ python3.14 -m norwegianblue python --color ye
usage: python3.14 -m norwegianblue [-h] [-f {html,json,md,markdown,pretty,rst,csv,tsv,yaml}] [-c {yes,no,auto}] [--clear-cache] [--show-title {yes,no,auto}] [-v]
[-V] [-w] [--pretty | --md | --rst | --json | --csv | --tsv | --html | --yaml]
[product ...]
python3.14 -m norwegianblue: error: argument -c/--color: invalid choice: 'ye' (choose from yes, no, auto)
```
```console
❯ python3.14 -m norwegianblue python --color ye
usage: python3.14 -m norwegianblue [-h] [-f {html,json,md,markdown,pretty,rst,csv,tsv,yaml}] [-c {yes,no,auto}] [--clear-cache] [--show-title {yes,no,auto}] [-v]
[-V] [-w] [--pretty | --md | --rst | --json | --csv | --tsv | --html | --yaml]
[product ...]
python3.14 -m norwegianblue: error: argument -c/--color: …
```
=> Suggest the correct choice when invalid (Python 3.14+)

.github/workflows/deploy.yml, .github/workflows/lint.yml, .github/workflows/release-drafter.yml, .github/workflows/require-pr-label.yml, .github/workflows/test.yml, .pre-commit-config.yaml, .yamlfmt.yaml, src/norwegianblue/cli.py
Generating PyPI's digital attestations should be enough (https://docs.pypi.org/attestations/), we don't _also_ need to use https://github.com/actions/attest-build-provenance.
Also test PyPy3.11 and update linting/config.
=> Only create PyPI digital attestations (PEP 740)

tests/test_norwegianblue.py
Needed for a clean slate between tests after https://github.com/termcolor/termcolor/pull/107.
To fix https://github.com/hugovk/norwegianblue/pull/248 and https://github.com/hugovk/norwegianblue/pull/249.
=> Clear termcolor cache after each test

src/norwegianblue/cli.py
Will be available for 3.14 beta:
https://docs.python.org/3.14/library/argparse.html#color
<table>
<tr>
<th>Before
<th>After
<tr>
<td>
<td>
</table>
=> Enable colour help for Python 3.14
